apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-env
  labels: 
    k8sfun.courselabs.co: configmaps
    app: configurable
data:
  Configurable__Release: 24.01.2
  Configurable__Environment: uat