apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-env
  labels: 
    k8sfun.courselabs.co: secrets
    app: configurable
data:
  Configurable__Release: from-configmap
  Configurable__Extra: from-configmap