apiVersion: v1
kind: Service
metadata:
  name: pi-np
  labels:
    k8sfun.courselabs.co: productionizing
spec:
  selector:
    app: pi-web
  ports:
    - name: http
      port: 8020
      targetPort: 80
      nodePort: 30020
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pi-lb
  labels:
    k8sfun.courselabs.co: productionizing
spec:
  selector:
    app: pi-web
  ports:
    - name: http
      port: 8020
      targetPort: 80
  type: LoadBalancer