apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
  labels:
    k8sfun.courselabs.co: ingress
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
      <body>
        <h1>
          Nothing to see here
        </h1>
      </body>
    </html>