apiVersion: v1
kind: Service
metadata:
  name: products-db
  labels:
    k8sfun.courselabs.co: hackathon
    app: widgetario
spec:
  ports:
    - port: 5432
      targetPort: postgres
  selector:
    app: widgetario
    component: products-db
  type: ClusterIP
  clusterIP: None