apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi-proxy-pv
  labels: 
    k8sfun.courselabs.co: persistentvolumes
    app: pi-proxy
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /volumes/pi-proxy
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: k8sfun
            operator: Exists