apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-logs-cluster
  labels:
    k8sfun.courselabs.co: rbac
roleRef:
  kind: ClusterRole
  name: podviewer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: courselabs
  apiGroup: rbac.authorization.k8s.io