apiVersion: v1
kind: Service
metadata:
  name: whoami-lab-np
  labels:
    k8sfun.courselabs.co: deployments
spec:
  selector:
    app: whoami-lab
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30020
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-lab-lb
  labels:
    k8sfun.courselabs.co: deployments
spec:
  selector:
    app: whoami-lab
    version: v1
  ports:
    - name: http
      port: 8020
      targetPort: 80
  type: LoadBalancer