apiVersion: v1
kind: Service
metadata:
  name: simple-proxy-internal
  labels:
    k8sfun.courselabs.co: statefulsets
spec:
  ports:
    - port: 8030
      targetPort: 80
  selector:
    app: simple-proxy
  clusterIP: None