apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: products-db
  labels:
    k8sfun.courselabs.co: hackathon
    app: widgetario
spec:
  selector:
    matchLabels:
      app: widgetario
      component: products-db
  serviceName: products-db
  replicas: 2
  template:
    metadata:
      labels:
        app: widgetario
        component: products-db
    spec:
      automountServiceAccountToken: false      
      containers:
        - name: app
          image: widgetario/products-db-replicated:21.03          
          envFrom:
            - secretRef:
                name: products-db-password
          ports:
            - containerPort: 5432
              name: postgres
          readinessProbe:
            tcpSocket:
              port: postgres
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 1
          livenessProbe:
            exec:
              command: ["pg_isready", "-h", "localhost"]
            periodSeconds: 60
            initialDelaySeconds: 20
            failureThreshold: 2
          resources:
            limits:
              cpu: 750m
              memory: 500Mi 
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data  
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        k8sfun.courselabs.co: hackathon
        app: widgetario
    spec:
      accessModes: 
       - ReadWriteOnce
      resources:
        requests:
          storage: 50Mi