apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-proxy
  namespace: front-end
spec:
  selector:
    matchLabels:
      app: pi-proxy
  template:
    metadata:
      labels:
        app: pi-proxy
        storage: container
    spec:
      containers:
        - image: nginx:1.18-alpine
          name: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-configmap
