apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-proxy-pvc
  labels: 
    k8sfun.courselabs.co: persistentvolumes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi